### ISSUE TITLE
Are there any plans to release training code?

### ISSUE THREAD

**Issue by 980202006** [jhtonyKoo/e2e_music_remastering_system#4]
This work makes sense, I want to apply a similar scheme to the mix, can you provide the training code?

**Comment by jhtonyKoo** [comment]
Dear user,
Currently, I do not have plans for releasing the training code. However, I believe the work is reproducible enough since we have provided every module (including data loader, mastering manipulator, and details of hyperparameters which are denoted in the "config.py" file) needed for the training procedure.
If you find a certain module to be unclear, please feel free to inquire about it.
